# https://tabler.io/icons

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/zach-stear/"

    [social.params]
        icon = "brand-linkedin"